### PR TITLE
Adding print top consuming processes option to check_load

### PR DESCRIPTION
**Pull request by sanchezfauste**
```
 -W, --print-top-warning
    Print top consuming processes on WARNING status
 -C, --print-top-critical
    Print top consuming processes on CRITICAL status
 -n, --procs-to-show=NUMBER_OF_PROCS
    Number of processes to show when printing top consuming
    processes. Not useful without -W or -C. Default value is 5
```

### CODE REVIEW

**Comment by sni** [comment]
I like the idea but i would make it less complicated. I would just add one additional option `-n` and print the top most processes if that number is greater than zero. I don't its neccessary to set different options for warnings and criticals.

**Comment by sanchezfauste** [comment]
@sni I agree with you, so I change it to:

```
 -n, --procs-to-show=NUMBER_OF_PROCS
    Number of processes to show when printing the top consuming processes.
    NUMBER_OF_PROCS=0 disables this feature. Default value is 0
```

**Comment by sni** [comment]
I am also a bit concered about the hard-coded `/bin/ps`. We have a `PS_COMMAND` constant which can be customized by the `./configure` script. And i assume this is for a reason. The `--sort=-pcpu` is probably not very portable across the various unix/linux systems.

```
%> ./configure --help 2>&1 | grep ps-
  --with-ps-command=PATH  Verbatim command to execute for ps
  --with-ps-format=FORMAT Format string for scanning ps output
  --with-ps-cols=NUM      Number of columns in ps command
  --with-ps-varlist=LIST  Variable list for sscanf of 'ps' output
```

I guess there is no easy fix for this.

**Comment by sanchezfauste** [comment]
I will fix the hard coded `/bin/ps`. What do you suggest for the `--sort=-pcpu`? Sort the output by hand using `qsort()`?

**Comment by sanchezfauste** [comment]
Hi @sni,

I have tried to re-implement using the macros defined for the `ps` command and sorting the procs list by CPU usage using `qsort` function. If procpcpu is not present on PS_VARLIST the procs are printed without sorting.

I hope this implementation solves the two problems that you have mentioned before.

**Comment by sni** [comment]
sorry this took a bit longer, finally merged

**Pull request merged**
