### PR TITLE
Changing remaining sscanf format specifier to unsigned long

### LINKED ISSUE #1874: check_swap: reports wrong swap size (~ factor 1024)
Since Version 2.3.3 OR Version 2.3.2 (haven't testet this one) check_swap reports the wrong swap size by about factor 1024. Version 2.3.1 was still OK.

Both, plugin-output and performance-data are wrong.

My systems do have a 1024 MB swap partition, check_swap reports 1204223 MB. Here an example output, same system, 2 different check_swap binaries:

```
#
# New Version, wrong output
#
~$ /usr/local/libexec/nagios/check_swap --version
check_swap v (monitoring-plugins 2.3.3)

~$ /usr/local/libexec/nagios/check_swap -c 25% -w 50%
SWAP OK - 100% free (1204223MB out of 1204223MB) |swap=1262719336448B;631359668200;315679834100;0;1262719336448

#
# Older Version, right output
#
~$ ./check_swap --version
check_swap v (monitoring-plugins 2.3.1)

~$ ./check_swap -c 25% -w 50%
SWAP OK - 100% free (1023 MB out of 1023 MB) |swap=1023MB;511;255;0;1023
```
OS: FreeBSD 13.1-RELEASE-p6

### PR DESCRIPTION
**Pull request by RincewindsHat**
Fixes #1874

### CODE REVIEW

**Review by waja — APPROVED** [review]
looks reasonable.

**Comment by RincewindsHat** [comment]
@waja Did something change on debian with the snmp stuff recently? https://github.com/monitoring-plugins/monitoring-plugins/actions/runs/5638335060/job/15272361748?pr=1876#step:3:7645

**Comment by waja** [comment]
> @waja Did something change on debian with the snmp stuff recently? https://github.com/monitoring-plugins/monitoring-plugins/actions/runs/5638335060/job/15272361748?pr=1876#step:3:7645

Not that I'm involved into this ... but:

https://tracker.debian.org/news/1446805/snmp-mibs-downloader-16-migrated-to-testing/
https://metadata.ftp-master.debian.org/changelogs//non-free/s/snmp-mibs-downloader/snmp-mibs-downloader_1.6_changelog

**Comment by RincewindsHat** [comment]
hm, are there some types missing in the mib collection after the upgrade to 1.6?

**Comment by waja** [comment]
> hm, are there some types missing in the mib collection after the upgrade to 1.6?

I don't know. Didn't looked into it deeper. As bookworm was released now, there might be introduced some breaking changes into Debian testing in the next time.

**Comment by waja** [comment]
Looking info https://github.com/waja/monitoring-plugins/actions/runs/5537784633/job/15284578236 which was running fine the last time, it looks like there was breaking changes recently.

**Comment by RincewindsHat** [comment]
Just upgrade this on my machine and I indeed get at least one error message which probably shouldn't be there.

```
Bad operator (INTEGER): At line 73 in /usr/share/snmp/mibs/ietf/SNMPv2-PDU
```

**Comment by RincewindsHat** [comment]
hm, regardless, this not associated with the changes in here, which are needed for #1874

**Pull request merged**
