### PR TITLE
Fix trailing whitespaces in C plugins

### PR DESCRIPTION
**Pull request by RincewindsHat**
I am kinda sorry about this, but I am highlighting trailing whitespaces in my editor and this annoys me.
So I executed `find . -type f -exec sed -i 's/\s\+$//' {} \;` in the plugins directory.
It would be nice if that could be made a permanent state.

### CODE REVIEW

**Review by sni — APPROVED** [review]
+1

**Comment by waja** [comment]
Beside this is a great move, it will make backporting of fixes into maint-2.3 much more complex.

**Comment by sni** [comment]
we should do this at some point and this point is as bad as the others. Cherry-Picking should be straight forward with `git cherry-pick -x -X ignore-all-space <commit>` since its really just white space changes.

**Comment by phibos** [comment]
Maybe something like [pre-commit](https://pre-commit.com/) could help reducing this type of errors before committing and pushing. I can provide a PR if you are interested.

**Comment by sni** [comment]
superseeded by #1680

**Pull request closed without merging**
