### PR TITLE
check_ping: added option for packet size

### PR DESCRIPTION
**Pull request by riskersen**
- added option (-s/--packetsize) for setting packet size (limited to 65528 Bytes, according to RFC791)
- added DEFAULT_PACKET_SIZE constant with 56 Bytes
- disabled ping check for UnixWare in autoconf: if condition and with_ping_command had different syntax

This is for issue #229

### CODE REVIEW

**Comment by riskersen** [comment]
I'll take a look

**Comment by riskersen** [comment]
Maybe someone have a look on it? Dunno why it keeps failing with a segfault..
```
./t/check_ping.t ......... Got signal 11 for command ./check_ping -H localhost -w 10,100% -c 10,100% -p 1 at ../NPTest.pm line 665.
# Looks like your test exited with 255 before it could output anything.
./t/check_ping.t ......... Dubious, test returned 255 (wstat 65280, 0xff00)
```

**Comment by RincewindsHat** [comment]
Sorry for no answer and for the following: I am voting to reject this. It is bad enough to parse cmdline output and have different `ping` implementations. No need to complicate this.

`check_icmp` has an option to do this and that should be enough IMHO.

@sni @waja  d'accord?

**Comment by waja** [comment]
we lived 7 years without anybody caring about this... so I would say there is not much interest in it

**Comment by sni** [comment]
well, if it works, i'd say why not. But at least this PR cannot be merged easily.

**Pull request closed without merging**
