### PR TITLE
Added check_mysql_slave

### PR DESCRIPTION
**Pull request by ip1981**
Supports MariaDB multi-source replication

### CODE REVIEW

**Comment by RincewindsHat** [comment]
Can this be integrated in `check_mysql`? may related to #1716

**Comment by GerMalaz** [comment]
> Can this be integrated in `check_mysql`? may related to #1716

As author of #1716:
The goal of both is the same (coincidentally, they both use -N for the replica name).
It modifies the existing check_mysql rather than adding a new plugin.
It supports both MariaDB and MySQL named replicas, rather than just MariaDB.

**Comment by waja** [comment]
As I was involved into the work removing `contrib/` I'm not a fan of adding new plugins (maybe nobody is caring).

**Comment by RincewindsHat** [comment]
Sorry for the wait. Integrating the test into an existing plugins makes more sense to me.

**Pull request closed without merging**
