### PR TITLE
CI: Switch back to testing

### PR DESCRIPTION
**Pull request by waja**
This reverses 9c1c3fc

### CODE REVIEW

**Comment by RincewindsHat** [comment]
@waja sorry for letting this lie around. Question is, should be switch back to testing.
One of the arguments there was, that testing on stable is probably less hassle.
At least seeing this from a dev perspective and less of the package maintainter one.

Maybe a middle way would be nice. doing regular testing on stable and have the same pipeline on manual or time-based trigger for testing?

**Comment by waja** [comment]
> One of the arguments there was, that testing on stable is probably less hassle.

We did not have much hassle in the past all over the years testing against Debian testing, as far as I remember. But had the opportunity to catch up issues with more recent software revisions.

**Comment by RincewindsHat** [comment]
we at least had the issue with the snmp mibs thing. But I don't really have strong opinion here. Might as well use testing.

**Comment by waja** [comment]
> we at least had the issue with the snmp mibs thing. But I don't really have strong opinion here. Might as well use testing.

Don't remember exactly the "fix", but wasn't that a kind of "more recent software revisions"? 🤔

**Review by RincewindsHat — APPROVED** [review]

**Comment by waja** [comment]
@RincewindsHat much appreciated

**Pull request merged**
