### PR TITLE
check_ping: Do not show RTA if no connection was possible

### PR DESCRIPTION
**Pull request by RincewindsHat**
Displaying the RTA in perfdata will confuse the system using this data  and falsify averages.

### CODE REVIEW

**Comment by RincewindsHat** [comment]
#1696

**Comment by sni** [comment]
i'd say it's not good practice to completely hide rta performance values, i'd prefer to keep it with a `U` to indicate unknown value as in https://www.monitoring-plugins.org/doc/guidelines.html#AEN201 under 8.
That way the number of performance values won't change.

**Comment by RincewindsHat** [comment]
Sounds reasonable

**Comment by sni** [comment]
sorry to be picky, but thinking about it, i'd say it would be better to even keep the thresholds. I mean, they still apply, even if the value cannot be determined.

**Comment by RincewindsHat** [comment]
hm, true enough, thresholds are there and valid.

**Review by sni — APPROVED** [review]

**Pull request merged**
