### PR TITLE
sslutils: use chain from client certificates

### PR DESCRIPTION
**Pull request by tobiaswiese**
sslutils used to load only the first certificate when it was given a
client certificate file.

Added tests for check_http to connect to a http server that expects a
client certificate (simple and with chain).

Because multiple additional certificates are now required for the check_http tests,
I created a script that regenerates the certificates.

Signed-off-by: Tobias Wiese <tobias@tobiaswiese.com>

### CODE REVIEW

**Comment by tobiaswiese** [comment]
rebased onto upstream/master

**Review by RincewindsHat — COMMENTED** [review]
Looks good to me, but there is a lot of magical perl :-)
I would like to have a second opinion on this.

**Review by sni — APPROVED** [review]
looks good to me

**Comment by waja** [comment]
so lets rush this into master! 🎉

**Pull request merged**
