### PR TITLE
only run tests on the master branch and on PRs

### PR DESCRIPTION
**Pull request by datamuc**

### CODE REVIEW

**Comment by waja** [comment]
What's the motivation about this?

**Comment by datamuc** [comment]
it's a suggestion for this:
```
<rincewind> does anybody know enough github to disable double tests if something is a
                       PR and a branch of the main repo?

**Comment by waja** [comment]
> <rincewind> does anybody know enough github to disable double tests if something is a
>             PR and a branch of the main repo?

But this PR disables also testing every branch beside master, doesn't it?

**Comment by datamuc** [comment]
> But this PR disables also testing every branch beside master, doesn't it?

correct, you might add `- maint-*` to the branches list. But other branches are only tested if you open a PR for them.

**Comment by RincewindsHat** [comment]
The original reason for my comment there was my annoyance, that creating a PR from a branch of the main repo would trigger the tests two times which seems rather unnecessary to me.
I would rather not have it like this PR suggests it though, since now contributors will not get tests before opening a PR.

Is there a good too just avoid triggering the pipelines multiple times?
Otherwise this could/probably solved organisationaly by just not working in the main repo

**Pull request closed without merging**
