### PR TITLE
check_http: support the concept of virtual ports

### PR DESCRIPTION
**Pull request by odenbach**
see issue #1026 , rebased against master.

### CODE REVIEW

**Comment by waja** [comment]
Hi,

I don't know if this can be merged by us, but it would super cool if you can rebase this PR against our recent master branch, as d73c57aa061a4c408701f980d1f8857b64433488 fixed some problems with our integration tests.

Thanks, Jan.

**Comment by odenbach** [comment]
Hi,

this patch _is_ against master, I rewrote the old one. It should integrate without any trouble.

What is this Travis CI build thing?

Regards,

Christopher

**Comment by waja** [comment]
Hi @odenbach, we are doing integration tests for commits and PRs on travis-ci.org. There was some problems why this tests was always failing recently. This is fixed with https://github.com/monitoring-plugins/monitoring-plugins/commit/d73c57aa061a4c408701f980d1f8857b64433488, but they were not on master when you created your PR. Anyway ... that would just be helpful as it helps you if your changes are passing all tests against your changed plugins.
Sometimes plugins are changed in such a way, that the tests needs to be adjusted too.

**Comment by odenbach** [comment]
Hi,

as I see it my patch and the patch above will not collide in any way as the changes are in totally different files. My patch does not change the default behaviour of check_http, so all tests should still pass as they did before.

Cheers,

Christopher

**Comment by odenbach** [comment]
Hi,

I realized that you marked the patch for release 2.2. What is the problem with it that it cannot be added right now? Can I help? Do you need any explanation what I am doing in it?

Thanks,

Christopher

**Comment by waja** [comment]
@odenbach 2.1.2 is just a bugfix release for 2.1.1. New features will go into 2.2. As this is an new feature, we targeted this for the next feature release.

**Comment by waja** [comment]
merging this into recent master (edcf7d64ee03f4b7fceb1ef470fb900572bce096), the tests succeeds: https://travis-ci.org/waja/monitoring-plugins/builds/85091328

**Comment by waja** [comment]
@odenbach it would be nice to have automated tests verifying this feature doesn't break in the future. This is what we are running automated on Travis CI for example.
Those checks are implemented in plugins/tests/check_http.t and plugins/t/check_http.t for check_http.

Many thanks for looking into this.

**Comment by odenbach** [comment]
Hi,

another attempt to get this upstream.

Thanks,

Christopher

**Comment by glensc** [comment]
@odenbach you were asked to rebase against master, but you created merge commit instead. i don't speak for monitoring-plugins, but usually project maintainers reject such pull requests and ask to rebase again.

please see "commits" tab how your pull request looks like:
https://github.com/monitoring-plugins/monitoring-plugins/pull/1352/commits

it should have only your commits, not merge commits.

anyway after rebase to master you need to git push -f to the same branch

**Comment by waja** [comment]
> aside: what is "http virtual port"? :D

The issie is actually, that when you pass a specific port to ```check_http```, this port is also used in the host header.
This might cause trouble on the server (or even better on web application level), when you are using port forwarding (or something similar) and the web application doesn't know about that and is expecting not to have a port (or a different one) in the host header, then ```check_http``` is using to connect to the server side.

**Comment by sni** [comment]
Merged with 2233b7aa. Thanks for your patience :-)

**Pull request closed without merging**
