### PR TITLE
Removing translation files

### PR DESCRIPTION
**Pull request by waja**
Unfortunately there is very less coverage of the translations and was not very much contribution recently this area. On the other side, maintaing the po files consumes a significant effort. For now we drop the translation files, but we can revert this change anytime in the future.

### CODE REVIEW

**Comment by waja** [comment]
Looks like `gl/` has issues when removing the translations.

**Comment by waja** [comment]
> Looks like `gl/` has issues when removing the translations.

Help is welcomed. :)

**Comment by RincewindsHat** [comment]
When I find the time :-)

**Comment by RincewindsHat** [comment]
@waja  better now? :-)

**Comment by waja** [comment]
> @waja  better now? :-)

WTF?!? How could I've overseen this?

**Comment by RincewindsHat** [comment]
so, go?

**Comment by waja** [comment]
Technical it looks good and checks are succeeding... so why not? ;)

**Review by RincewindsHat — APPROVED** [review]

**Pull request merged**
