### PR TITLE
check_http: Fixing unchunking body when no body is present

### PR DESCRIPTION
**Pull request by trickert76**
When no-body is enabled and the server responses with a chunked body, there is always an unknown response from check_http because it tries to read the body, which is not present.

### CODE REVIEW

**Review by RincewindsHat — APPROVED** [review]
Looks good to me, thank you very much.

**Comment by paladox** [comment]
Is there any chance this could be backported to https://packages.debian.org/bookworm/monitoring-plugins?

**Comment by RincewindsHat** [comment]
Hi @paladox, maybe waja is interested to do that. Otherwise just use `check_curl` which does the same as `check_http` but better.

**Comment by paladox** [comment]
Thanks! Switched to check_curl and seems to fix it for me.

**Comment by waja** [comment]
There was opened a bugreport in the Debian BTS: https://bugs.debian.org/1061956

**Comment by RincewindsHat** [comment]
@waja Backport #1901 maybe?

**Comment by waja** [comment]
This was requested for approval: https://bugs.debian.org/1062063

**Comment by waja** [comment]
Should be included into the next point release (this weekend).

**Comment by teutat3s** [comment]
When would be the next scheduled release? We are really looking forward for the integration of this fix.

**Comment by RincewindsHat** [comment]
we don't have scheduled releases, but if @waja  feels like it, we could do one :-)

**Pull request merged**
