### PR TITLE
check_disk: Add more filesystems to ignore by default

### LINKED ISSUE #1748: check_disk: Selectively exclude squashfs, tracefs and tmpfs by default.
Hi,

In Ubuntu we're taken up the issue of monitoring-plugins#1608 (false positive DISK CRITICAL error), as we're encountering some DISK UNKNOWN messages as a consequence (https://bugs.launchpad.net/ubuntu/+source/monitoring-plugins/+bug/1940916). This bug is a side-effect of bug 1827159, where the synthetic filesystems (tmp, squash, trace) were excluded by default to avoid false positives: if the user wants to explicitly check such filesystem (by including them in the command line) or check a mount point based on one of them, the result was DISK UNKNOWN (as it was excluded by default and exclusion takes precedence over inclusion).

To strike a balance between the two, we propose here a solution that works on Ubuntu and that we are considering accepting. The approach here has been to exclude this type of filesystem only if it is neither included via path (option -p) nor via include (option -N).

 To minimize some possible impact, these changes are located after all the arguments logic has been done, not altering what the user has requested via command line.

### PR DESCRIPTION
**Pull request by RincewindsHat**
Replaces #1749 
Fixes #1748

### CODE REVIEW

**Comment by waja** [comment]
good catch by the CI pipeline :)

**Comment by RincewindsHat** [comment]
Anyone got an idea why that fails?

**Comment by KriSchu** [comment]
> Anyone got an idea why that fails?

Tests and the test setup are absolutely not my expertise, so please excuse if this is completely stupid, but isn't it failing because, by your code change you exclude tmpfs filesystems, but the test pipeline adds tmpfs filesystems to the docker container which is running the tests? 
At least I think that this could explain, why the test expects two filesystems, but found 0 filesystems in the output:
```
#   Failed test 'Got two mountpoints in output'
#   at ./t/check_disk.t line 36.
#          got: 0
#     expected: 2
```

The other check is about the exit code being 3 (Unknown), while 0 (OK) is expected.
If both filesystems are excluded, that there is no filesystem to check and the plugin prints:
`DISK UNKNOWN - No disks were found for provided parameters;|`

I believe the test setup could explain these failed tests and that it can be solved by either changing to a different fs type or by modifying the tests.

**Comment by RincewindsHat** [comment]
That sounds like a likely explanation. At this point I see a general problem with those changes here. I am not able to remove stuff from the exclusion list during runtime, so this is equivalent to saying "this plugin ignores those filesystem types ALWAYS" which is going to far IMHO.

**Comment by waja** [comment]
@RincewindsHat so same counts for #1749?

**Comment by RincewindsHat** [comment]
@waja sorry, this went under. Yes, same problem. Question is whether we want to ignore those filesystems ALL THE TIME.

**Comment by RincewindsHat** [comment]
Hard coding the ignored filesystems is probably a bad idea in general.
There I am closing this again until I find a better solution.

**Pull request closed without merging**
