### PR TITLE
Try to detect if there are translation updates via CI

### PR DESCRIPTION
**Pull request by waja**
I've prepared a draft to detect missing translation updates in a way. I don't know if that's the golden way ... but it's a starting point.

### CODE REVIEW

**Comment by RincewindsHat** [comment]
hm, I do like the idea, but can we rely on the ordering of translation messages in the `.po` files?
I mean, if we generate the translation files two times in a row, do we get the same files? Otherwise this will generate a lot(!) of false positives

**Comment by waja** [comment]
> hm, I do like the idea, but can we rely on the ordering of translation messages in the `.po` files?

I did test the pipeline with an updated `po/` and it worked flawless ... yes, this is no safe proof, but we can throw it away again, when it will be a hassle.

**Comment by waja** [comment]
Okay ... do we wonna merge it?

**Review by RincewindsHat — APPROVED** [review]
Let's try this

**Pull request merged**
