### PR TITLE
run tests with debian:stable

### PR DESCRIPTION
**Pull request by datamuc**
debian:testing is broken

### CODE REVIEW

**Comment by waja** [comment]
Can you please explain, what is broken?

**Comment by datamuc** [comment]
They removed squid

https://github.com/monitoring-plugins/monitoring-plugins/actions/runs/6302177559/job/17108828316

**Comment by waja** [comment]
So maybe anybody has to investigate further and fix the issue within testing.

**Comment by waja** [comment]
In a First view, the issue seems temporary by a transition: https://release.debian.org/transitions/html/auto-openldap.html

**Comment by datamuc** [comment]
> In a First view, the issue seems temporary by a transition: https://release.debian.org/transitions/html/auto-openldap.html

Now we are in opinionland, so here is mine:

Sure, I'm convinced that this is temporary. But for an action that is run on every PR I want something more reliable. If you want to test your stuff against the next version of debian I would suggest an action that runs on a regular basis on the master/main branch and opens an issue if it fails or something like that.

But that's just my 2 ct.

**Review by RincewindsHat — APPROVED** [review]
Well, until the transition is done, I would like to have tests.
We can switch back later or add another pipeline for testing in general

**Pull request merged**
