### PR TITLE
Missing oldlog now aborts check_log

### PR DESCRIPTION
**Pull request by RincewindsHat**

### CODE REVIEW

**Comment by RincewindsHat** [comment]
Updates #1659

**Comment by sni** [comment]
I don't think this is a good idea as it potentially would lead to lots of unknowns after a update and i am a fan of the "least surprise" approach.

**Comment by RincewindsHat** [comment]
To my understanding the script doesn't even work without `oldlog`, but I might be wrong

**Review by sni — APPROVED** [review]

**Comment by sni** [comment]
sorry, my bad. I forgot how check_log.sh worked :-) Looks good then.

**Pull request merged**
