### PR TITLE
check_ups: additional alarm conditions

### PR DESCRIPTION
**Pull request by RincewindsHat**

### CODE REVIEW

**Comment by RincewindsHat** [comment]
Fixes #1708

**Comment by sbraz** [comment]
Hi @RincewindsHat, I just built the check with this patch and it works nicely :) I know this is a draft but I wanted to share my real-world test on a UPS which currently has an alarm:
```
UPS CRITICAL - Status=Online, ALARM Batt=100.0% Load=28.0% Real power=269.0W | battery=100%;;;0;100 load=28%;;;0;100 realpower=269W;;;0;
```

FYI the status looks like this:
```
# upsc eaton | grep -i alarm
ups.alarm: Battery voltage too low!
ups.status: ALARM OL
```

**Comment by RincewindsHat** [comment]
Hi @sbraz,
Thanks for the Feedback.

Would be nice if the output would shine some more light on the problem. Maybe something can be added to explain the problem better.

**Comment by sbraz** [comment]
I think anyone who sees an ALARM in their output will probably check the output of `upsc` so I wouldn't worry too much about it. Thanks for the merge! Do you have any plans to make a new release in the near future?

**Comment by RincewindsHat** [comment]
It is not merged yet, I just pulled the current master in.
For a merge a review of someone ( @sni ) would be necessary.

**Comment by sbraz** [comment]
Oh my bad, I misread the email notification :)

**Comment by RincewindsHat** [comment]
no problem, but I can't really say anything about a merge or release. Not that many people are working on this...

**Review by sni — APPROVED** [review]

**Pull request merged**
