### PR TITLE
check_disk_smb: allow checking 0-sized resource (ex. IPC$)

### PR DESCRIPTION
**Pull request by glensc**
patch by Marek Marczykowski marmarek@staszic.waw.pl

originated from pld-linux
https://github.com/pld-linux/monitoring-plugins/commits/auto/th/monitoring-plugins-2.1.2-1/nagios-plugins-check_disk_smb-zero-cap.patch

### CODE REVIEW

**Comment by waja** [comment]
@glensc can you please tell us, what's the purpose of this change?

**Comment by waja** [comment]
(It seems to be over years in PDL Linux, I think if this would be an issue, this would have been adjusted there. :)

**Comment by glensc** [comment]
I don't have any more info than shared here. It was me carrying over patches from pld linux.

as much I recall when used Windows from the past, `IPC$` may be some share name: `\\hostname\ipc$`

**Comment by RincewindsHat** [comment]
So, to my understanding (which is limited, because this is perl and windows), this prevents a division by zero in that line.
Since the value is only used in the output later it does not disturb other functionality.

**Review by RincewindsHat — APPROVED** [review]
Can't hurt I think

**Pull request merged**
