### PR TITLE
add LOAD prefix to load plugin

### PR DESCRIPTION
**Pull request by haraldj**
just a cosmetic fix so the load plugin display a LOAD prefix before check results

### CODE REVIEW

**Comment by sni** [comment]
agreed, that would match better with our other plugins. However, may i suggest a simple:
`printf("LOAD %s - %s|", state_text(result), status_line);`

**Comment by haraldj** [comment]
Dear Sven Nierlein,

> agreed, that would match better with our other plugins. However, may i suggest
> a simple:
> printf("LOAD %s - %s|", state_text(result), status_line);

ok, changed my patch this way, thanks for the heads up.

Kind regards
Harald Jenny

**Comment by RincewindsHat** [comment]
Hi @haraldj , 
Seems like you checked in the smtp change again :-)

**Comment by sni** [comment]
Also please adjust the tests in https://github.com/monitoring-plugins/monitoring-plugins/blob/master/plugins/t/check_load.t

**Comment by haraldj** [comment]
> Hi @haraldj ,

Hi,

> Seems like you checked in the smtp change again :-)

yes seems I'm not fit enough currently to do github ;-).

Thanks
Harald

**Comment by haraldj** [comment]
Hi

> Also please adjust the tests in https://github.com/monitoring-plugins/
> monitoring-plugins/blob/master/plugins/t/check_load.t

please check #1694 it should be correct now and complete.

Kind regards
Harald

**Pull request closed without merging**
