### PR TITLE
check_ircd: IPv6 support

### PR DESCRIPTION
**Pull request by oxzi**
The prior bindRemote function was restricted to IPv4 by explicitly using address family specific functions as pack_sockaddr_in or unparametrized gethostbyname. Since Perl 5.14, released in early 2013, there is IO::Socket::IP, which supports lookups and connects for a dual stacked network.

By switching the connection establishment code, the plugin is now able to establish connections to IPv6-only hosts. Furthermore, additional -4 and -6 flags were introduced to enforce a specific address family.

> $ netstat -p tcp -ln | grep 6667
> tcp6         0      0  *.6667                 *.*                    LISTEN
> $ ./plugins-scripts/check_ircd -H localhost
> IRCD ok - Current Local Users: 4
> $ ./plugins-scripts/check_ircd -H localhost -4
> IRCD UNKNOWN: Could not start socket (Connection refused)
> $ ./plugins-scripts/check_ircd -H localhost -6
> IRCD ok - Current Local Users: 4

### CODE REVIEW

**Review by sni — APPROVED** [review]
looks good to me.

**Comment by sni** [comment]
thanks. The changes itself look ok, i assume you tested the changes locally? Because, as far as
i see, there are no unit tests for this plugin, not even a perl syntax check :-)

**Comment by oxzi** [comment]
Thanks for your fast reply.

> The changes itself look ok, i assume you tested the changes locally? Because, as far as i see, there are no unit tests for this plugin, not even a perl syntax check :-)

The output in my original post was from a system checking itself with this check. Furthermore, the altered plugin runs in my small monitoring setup since yesterday. I just tested it against a bigger IRC network with altering IP address family settings and against an IPv4- and IPv6-only address:
```
$ ./plugins-scripts/check_ircd -w 2500 -c 3000 -H irc.libera.chat
IRCD ok - Current Local Users: 2201
$ ./plugins-scripts/check_ircd -w 2500 -c 3000 -H irc.libera.chat -4
IRCD ok - Current Local Users: 2147
$ ./plugins-scripts/check_ircd -w 2500 -c 3000 -H irc.libera.chat -6
IRCD ok - Current Local Users: 2201
$ ./plugins-scripts/check_ircd -w 2500 -c 3000 -H irc.ipv4.libera.chat
IRCD ok - Current Local Users: 2186
$ ./plugins-scripts/check_ircd -w 2500 -c 3000 -H irc.ipv4.libera.chat -6
IRCD UNKNOWN: Could not start socket (Invalid argument)
$ ./plugins-scripts/check_ircd -w 2500 -c 3000 -H irc.ipv6.libera.chat
IRCD ok - Current Local Users: 2205
$ ./plugins-scripts/check_ircd -w 2500 -c 3000 -H irc.ipv6.libera.chat -4
IRCD UNKNOWN: Could not start socket (Invalid argument)
```

However, just for the reference: I have close to zero experiences with Perl. The change, which was luckily small, was created mostly by cross reading the documentation.

**Comment by RincewindsHat** [comment]
fixes #822

**Comment by RincewindsHat** [comment]
fixes #1019

**Comment by RincewindsHat** [comment]
probably closes  #824 (although I am not completely sure about that)

**Comment by oxzi** [comment]
Thanks for searching the issue tracker for me, @RincewindsHat. I somehow missed that and just went straight into writing a patch.

> probably closes #824 (although I am not completely sure about that)

I guess, this should close #824. Next to the now obsolete `hostname` acquiring method, the attached patch uses `IO::Socket::INET` for connection establishment. By using `IO::Socket::IP` this PR addresses the same issue regarding hand-crafted connections, but also covers IPv6.

**Comment by RincewindsHat** [comment]
Thank you a lot @oxzi :-)

**Pull request merged**
