### PR TITLE
check for ping -{4,6} from new upstream iputils

### PR DESCRIPTION
**Pull request by eworm-de**

### CODE REVIEW

**Comment by eworm-de** [comment]
This is the downstream report from Arch Linux bug tracker:
https://bugs.archlinux.org/task/48338

**Comment by waja** [comment]
#1412 seems related

**Comment by waja** [comment]
@eworm-de if it isn't too much hassle for you, can you please [rebase](http://stackoverflow.com/a/7929499) your PR against master? This might fix the travis checks.

**Comment by eworm-de** [comment]
Already did that before you requested. ;)

**Comment by waja** [comment]
Is this still needed? It's rotting since 5 years and longer but things seems to work without that change.

**Comment by eworm-de** [comment]
For Arch Linux this works as we configure with `--with-ping-command='/usr/bin/ping -4 -n -U -w %d -c %d %s' --with-ping6-command='/usr/bin/ping -6 -n -U -w %d -c %d %s'`...

https://gitlab.archlinux.org/archlinux/packaging/packages/monitoring-plugins/-/blob/main/PKGBUILD?ref_type=heads#L31

**Comment by waja** [comment]
I guess this is be done by every maintainer. In Debian we [do](https://salsa.debian.org/nagios-team/monitoring-plugins/-/blob/master/debian/rules#L54-60):
```
ifeq ($(DEB_HOST_ARCH_OS),linux)
PING_CONFIGURE_ARGS = --with-ping-command="/bin/ping -4 -n -U -w %d -c %d %s" \
                      --with-ping6-command="/bin/ping -6 -n -U -w %d -c %d %s"
else
PING_CONFIGURE_ARGS = --with-ping-command="/bin/ping -n -w %d -c %d %s" \
                      --with-ping6-command="/bin/ping6 -n -w %d -c %d %s"
endif
```

**Comment by waja** [comment]
If nobody is complaining, I would prefer to close this one ...

**Comment by eworm-de** [comment]
Configuring at build time is the way to go.

**Pull request closed without merging**
