### PR TITLE
check_disk: return UNKNOWN instead of CRITICAL where…

### PR DESCRIPTION
**Pull request by Al2Klimov**
… a disk's usage isn't available

### CODE REVIEW

**Comment by Al2Klimov** [comment]
* [x] unit tests
* [x] master rebase
* [x] actual email

**Review by RincewindsHat — APPROVED** [review]
Looks sane.

**Comment by RincewindsHat** [comment]
I think this behaviour would be ok, but there might be different opinions on that topic.
Someone might be surprised by finding that a suddenly vanished file system is not a reason for `CRITICAL`. Maybe add a `--ignore-missing` ?

**Comment by sni** [comment]
i'd say you might argue about this. If we merge this, someone will come soon and want to change it back. For both variants there are valid scenarios. So i'd vote for a switch to change the behaviour but keep the default as is.

**Comment by KriSchu** [comment]
Hi, I don't like the idea to return UNKNOWN when the filesystem is missing without an option to have a critical alert.
There are definitely scenarios where one wants an alert for missing filesystems, because they actually should be mounted on the server and a missing FS is a problem state.

I hope the PR #1801 is a feasible solution for the requirement not to get alerts for unavailable FS.
But please, don't merge this code change, as it would be a breaking change for us.

**Pull request closed without merging**
