### PR TITLE
check_ssh: patches from op5

### PR DESCRIPTION
**Pull request by catharsis**
Here are a few check_ssh patches that I've written in response to various bug reports we've received at op5. I apparently put off sending them upstream for too long, because I had a couple of merge conflicts. If you're able to run the tests before merging, that'd probably be a good idea, in the case of a mismerge.

### CODE REVIEW

**Comment by skottler** [comment]
@catharsis need to do a more complete review on this, but overall looks good!

Can you take a look at the issue with the test harness?

**Comment by catharsis** [comment]
@skottler There we go. Mismerge indeed. :-)

**Comment by skottler** [comment]
Hey sorry for neglecting to review this. Will get to it tomorrow.

**Comment by catharsis** [comment]
Going through my outstanding PRs. Anything blocking this from getting merged?

**Comment by RincewindsHat** [comment]
Why wasn't this merged?

**Comment by waja** [comment]
no special reason. :)

**Comment by waja** [comment]
Any reason didn't merge it after @sni approved it? :) https://build.opensuse.org/package/view_file/server:monitoring/monitoring-plugins/monitoring-plugins.spec?expand=1 and https://build.opensuse.org/package/view_file/server:monitoring/monitoring-plugins/monitoring-plugins-2.3.3-check_ssh.t_-_improve_testing.patch?expand=1 looks if this might a good idea.

**Comment by RincewindsHat** [comment]
replaced by #1738

**Pull request closed without merging**
