### PR TITLE
check_http: Remove Bug in page length calculation

### PR DESCRIPTION
**Pull request by thomas1147**
With the current version of check_http we have issues with some Websites that the page length is not correctly calculated. It stays in reading the loop (line 1092) and as a result we got a timeout:

```
./plugins/check_http -v '-u' '/rest/health' '-w' '5.000000' '-c' '15.000000' '-t' 2 '--onredirect=follow' '-j' 'GET' '--sni' '-p' '8180' 'myserver.dc.rewe.local' 'myserver.dc.local'                                      option f:4
GET /rest/health HTTP/1.1
User-Agent: check_http/v2.3.2 (monitoring-plugins 2.3.2)
Connection: close
Host: myserver.dc.local:8180

CRITICAL - Socket timeout after 16 seconds
```

In the Nagios Plugins this was fixed with the following commit: https://github.com/nagios-plugins/nagios-plugins/commit/9b75c1ac86b7d9a898c2c6434c4a0fcd2dd8d611

I've implemented the same with this commit in the check_http version of the monitoring-plugins, and it is working:

```
 ./plugins/check_http -v '-u' '/rest/health' '-w' '5.000000' '-c' '15.000000' '-t' 2 '--onredirect=follow' '-j' 'GET' '--sni' '-p' '8180' 'myserver.dc.local' 'myserver.dc.local'
option f:4
GET /rest/health HTTP/1.1
User-Agent: check_http/v2.3.2 (monitoring-plugins 2.3.2) Connection: close
Host: myserver.dc.local:8180


http://myserver.dc.local:8180/rest/health is 82 characters STATUS: HTTP/1.1 200 OK
**** HEADER ****
cache-control: no-cache
content-type: */*
content-length: 0
**** CONTENT ****

HTTP OK: HTTP/1.1 200 OK - 82 bytes in 0.004 second response time |time=0.004264s;5.000000;15.000000;0.000000;16.000000 size=82
```

Best Regards
Thomas

### CODE REVIEW

**Comment by RincewindsHat** [comment]
Thank you for reporting this issue, I edited this post slightly to make it more readable (code blocks). I will take a look at it, when I find the time.

**Comment by sni** [comment]
Is there anything wrong with those pages? Is it anything that could be put in a test case?

**Comment by RincewindsHat** [comment]
what does `check_curl` do here?

**Comment by RincewindsHat** [comment]
Sorry for the wait.
I am not willing to invest more time in fixing stuff in `check_http` if `check_curl` is there and (hopefully) working better.
Therefor I am closing this PR.

**Pull request closed without merging**
