### PR TITLE
Point to Icinga Exchange instead of dead Monitoring Exchange

### PR DESCRIPTION
**Pull request by RincewindsHat**

### CODE REVIEW

**Comment by waja** [comment]
Seems reasonable. Even, I don't like adjusting more things in one commit/PR. :)

**Comment by RincewindsHat** [comment]
Sorry, those were some trivial whitespace thingies and I couldn't resist to `sed` them. Should I change them back?

**Comment by waja** [comment]
> Sorry, those were some trivial whitespace thingies and I couldn't resist to `sed` them. Should I change them back?

Nope. But next time it would be great if you can split this into separate commits, better issues.

Please don't get me wrong. It's great that this all is fixed. But with my (Debian) maintainers hat on, sometimes it's needed to patch specific issues (upstream) and if you have mixed commits, it might be needed to fiddle things out of one patch to address just the exact problem (to get things upstream accepted for example).

Thanks, Jan.

**Comment by RincewindsHat** [comment]
You are right, of course. I Will try to keep that in mind for the future. If you are happy otherwise, could you review the change?

**Review by waja — APPROVED** [review]
Removed taring whitespaces are fine. Migrating away from monitoringexchange.org as it is dead seems also reasonable.

**Pull request merged**
