### PR TITLE
Rename output to cmd_output

### PR DESCRIPTION
**Pull request by RincewindsHat**
The name of the type `output` is hugely misleading, so I changed it to `cmd_output`.

### CODE REVIEW

**Comment by RincewindsHat** [comment]
@sni @waja Comments?

**Comment by sni** [comment]
tbh, i don't see how the name output is hugely misleading?

**Comment by RincewindsHat** [comment]
I guess I went through that code at the time and was wondering how the output (think "stuff this programm should print") was in there and why it was handled this way.
It took me some time to understand, that it is the output of another command.
I guess, that annoyed me a bit.

**Comment by waja** [comment]
Another change that makes it harder to integrate patches from np ...

**Comment by RincewindsHat** [comment]
ok ok, I was just very irritated

**Pull request closed without merging**
