### PR TITLE
check_ssh: patches from op5

### PR DESCRIPTION
**Pull request by RincewindsHat**
Reintroduce #1322

### CODE REVIEW

**Comment by wbollock** [comment]
This should fix the core issue behind #1497 correct? Not the switch but the empty response: cb0b3e2

**Comment by waja** [comment]
@RincewindsHat is this just a draft PR actually?

**Comment by RincewindsHat** [comment]
@waja I guess so, I mainly wanted to rebase the changes against the current master. Should probably have been a draft

**Comment by RincewindsHat** [comment]
@wbollock Sorry, don't know why I didn't answer. Might be the answer to your problem, but I do not yet comprehend what all of the changes do

**Comment by RincewindsHat** [comment]
Tests are running now. Ready for review again.

**Review by sni — APPROVED** [review]

**Comment by RincewindsHat** [comment]
Thank you @catharsis :-)

**Pull request merged**
