### PR TITLE
check_dns: improve support for checking multiple addresses

### PR DESCRIPTION
**Pull request by DerDakon**
Improve the handling of multiple IPs in check_dns: my use case is a set of hosts with 2 addresses each (IPv4 + IPv6), which I don't want to split into "IPv4 is smaller in string compare than IPv6" and "the others". And I want to check that the exactly the addresses I have configured are returned, no more, no less.

This more or less intentionally breaks the previously working "pass addresses as comma separated string and compare that". The combination of -L and multiple -a does the same without breaking randomly on every IP change. I don't care. YMMV.

### CODE REVIEW

**Comment by DerDakon** [comment]
Ping?

**Comment by DerDakon** [comment]
Ping?

**Comment by DerDakon** [comment]
Ping?

**Comment by DerDakon** [comment]
ping?

**Comment by DerDakon** [comment]
ping?

**Comment by sni** [comment]
thanks and merged. Sorry, we are all somehow quite busy.

**Pull request merged**
