### PR TITLE
check_http: chunked encoding support

### PR DESCRIPTION
**Pull request by abrender**
This modification to check_http.c enables chunked encoding support with the '-U' option. It is disabled by default for backwards compatibility.

### CODE REVIEW

**Comment by sykosoft** [comment]
@weiss @waja We've been patiently waiting for this to be included, as it affects a lot of checks we try to do. Any news on when this might be fixed?

**Comment by waja** [comment]
@sykosoft looking into the troubles introduced by integrating this feature by nagios-plugins into their project, it might be a good idea to have this well tested before integrating this into an office release.

**Comment by ekeih** [comment]
Hi,
we can confirm that this issue still exists.
@weiss could you write some details about your comment from 2013 about several issues with this PR? Maybe this would help other people to understand what we need to do to fix this very old but still annoying issue.
Thank you in advance!

**Comment by weiss** [comment]
> Maybe this would help other people to understand what we need to do to fix this very old but still annoying issue.

I think the proper fix is to switch to [`check_curl`][1] which is currently being developed and tested in the [`feature_check_curl`][2] branch.

[1]: https://github.com/monitoring-plugins/monitoring-plugins/blob/feature_check_curl/plugins/check_curl.c
[2]: https://github.com/monitoring-plugins/monitoring-plugins/tree/feature_check_curl

**Comment by ekeih** [comment]
Thank you for this super fast response! :) We will check out check_curl!

**Comment by weiss** [comment]
> We will check out check_curl!

Cool, if you run into any issues, please report them.  It should be mostly compatible with `check_http` by now, i.e. it's supposed to work as a drop-in replacement except for corner cases.

**Comment by ekeih** [comment]
What is currently needed to merge check_curl into the master branch? Only more testing or anything else?

We will try to run check_curl parallel to check_http for a while. This way we can check if they behave the same way for ~2500 checks.

**Comment by ekeih** [comment]
Okay, not sure if this is a coincidence but here is a PR: https://github.com/monitoring-plugins/monitoring-plugins/pull/1535 :)

**Comment by waja** [comment]
`check_curl`has landed in 2.3.

**Comment by michaelsmoody** [comment]
Wow. Well. I'd honestly lost track of this by now. But, that's excellent news.

**Comment by RincewindsHat** [comment]
So, this is probably resolved? Can this PR be closed?

**Pull request closed without merging**
