### PR TITLE
check_http: Add test for virtual port usage

### PR DESCRIPTION
**Pull request by odenbach**
Hi,

next try with a dev branch, hope I did it right this time (I am still on my first steps with git).

The test should run for the non-SSL and SSL-server, so the natural way to implement both tests was in the run_common_tests routine. To make the test aware of the used port I had to add the virtual port to the hostname (127.0.0.1:80 instead of 127.0.0.1). This does not make any difference for the already implemented tests and works fine for my new one.

What I did:

- change number of tests
- add new test URL to the http daemons
- add two new tests to the run_common_tests routine
- add the virtual port to the hostname

If you do not like the idea of adding the virtual port for all other checks as well (which are not aware of the virtual port), I would suggest passing hostname, real port and virtual port as individual parameters and have the routine use them as needed. I can implement that if you prefer it.

Any more comments?

Thanks,

Christopher

### CODE REVIEW

**Comment by odenbach** [comment]
What is wrong with mariadb in the Travis Environment?

**Comment by waja** [comment]
> What is wrong with mariadb in the Travis Environment?

Looks like an issue on Travis-CI: https://www.google.de/#q=Unable+to+correct+problems,+you+have+held+broken+packages.&tbs=qdr:d

**Comment by odenbach** [comment]
Hi,

next try to add a test for my check_http changes which got integrated.

Cheers,

Christopher

**Comment by odenbach** [comment]
Hi,

could you please have a look at my latest changes? Any comments?

**Comment by sni** [comment]
Could you please rebase your PR on the latest master? It's quite hard to tell what you actually changed.

**Comment by odenbach** [comment]
Like this?

**Comment by sni** [comment]
not really, this PR still contains all other commits since then. I meant a "rebase". Like
`git rebase master` instead of a `git merge`. You might have to force push the changes then, since you changed the history of your branch then. (Make a backup of you changes before you do that :-)
If the rebase doesn't work for some reasons, just delete the branch or create a new one from the fresh master and apply your changes there.

**Comment by odenbach** [comment]
So please have a look at #1474.

**Comment by sni** [comment]
great, this looks much cleaner. I will close this one.

**Pull request closed without merging**
