### PR TITLE
Remove trailing whitespaces from ALL the files

### PR DESCRIPTION
**Pull request by RincewindsHat**
So, now I removed trailing whitespaces from everything (except the *.tar.gz files (archives in a repo??)).
I didn't look like it broke anything.

### CODE REVIEW

**Comment by RincewindsHat** [comment]
well, anything I missed before I mean

**Comment by sni** [comment]
agreed, i like it. Also i would like to add a unit test to ensure no new trailing whitespace will be added again.

**Comment by RincewindsHat** [comment]
@sni: Add a pre-push hook and a corresponding section in `Makefile.am`. Hopefully this is not too annoying

**Comment by phibos** [comment]
I'm using [pre-commit](https://pre-commit.com/) to do this. It provides an pre-commit git hook and is integrated in the GitHub workflow and can check all pull requests before merging.

If you are interested I can provide a PR with the required files.

**Comment by waja** [comment]
> If you are interested I can provide a PR with the required files.

I'd like to. :)

**Comment by RincewindsHat** [comment]
Outdated by now.

**Pull request closed without merging**
