### PR TITLE
Fix error in translation file introduced during a merge

### PR DESCRIPTION
**Pull request by RincewindsHat**
sorry about that. Should have let the test case run through

### CODE REVIEW

**Comment by RincewindsHat** [comment]
@waja sorry to be annoying. This should fix the problem of #1912

**Comment by franzs** [comment]
@RincewindsHat Sorry for nitpicking. :innocent:

The change doesn't reflect the output of `make update-po` which produces just one line in `fr.po` and `de.po`:

```
msgid "name and password. A configuration file must be present. The format of"
```

So my suggestion is to run `make update-po` to have a better basis for further changes.

**Comment by RincewindsHat** [comment]
@franzs satisfied? :-)

**Comment by franzs** [comment]
Much better... :nerd_face: Thanks, @RincewindsHat!

**Pull request merged**
