### PR TITLE
check_curl: add haproxy protocol option

### PR DESCRIPTION
**Pull request by emriver**
This PR adds a new `--haproxy-protocol` flag to `check_curl`.

The new flag enables the libcurl option `CURLOPT_HAPROXYPROTOCOL` to send haproxy protocol header v1 at the beginning of the connection.

### CODE REVIEW

**Comment by andreasbaumann** [comment]
The proposed change looks straightforward. I just have no means to test it, even
manually,

**Comment by andreasbaumann** [comment]
The proposed change looks straightforward. I just have no means to test it, even
manually,

**Comment by waja** [comment]
https://www.haproxy.com/documentation/haproxy-configuration-tutorials/client-ip-preservation/enable-proxy-protocol/ looks straight forward. https://www.haproxy.com/blog/how-to-run-haproxy-with-docker has some useful information how to spin up haproxy using docker.

The question that comes to my mind is, how could look a test case.

**Comment by andreasbaumann** [comment]
I devided a haproxy.conf:

```
global
    maxconn     20000
    log         127.0.0.1 local0
    user        haproxy
    chroot      /usr/share/haproxy
    pidfile     /run/haproxy.pid
    stats socket /run/haproxy/admin.sock mode 660 level admin
    daemon

frontend  main
    bind :80
    mode                 http
    log                  global
    option               httplog
    option               dontlognull
    maxconn              8000
    timeout              client  30s

    default_backend             static

backend static
    mode        http
    balance     roundrobin
    timeout     connect 5s
    timeout     server  5s
    server      static 127.0.0.1:8080 check
    option      httpchk
    http-check  connect port 8080
    http-check  send meth GET uri / ver HTTP/1.1 hdr host localhost
    http-check  expect status 200
```

I have an `apache` webserver on port 8080 with just return the index page for
the web root.

```
curl -vvk http://localhost:8080/
```

works

```
curl -vvk http://localhost:80/
```

too, on haproxy side I see:

```
00000001:main.accept(0005)=000c from [127.0.0.1:50828] ALPN=<none>
00000001:main.clireq[000c:ffffffff]: GET / HTTP/1.1
00000001:main.clihdr[000c:ffffffff]: host: localhost
00000001:main.clihdr[000c:ffffffff]: user-agent: curl/8.6.0
00000001:main.clihdr[000c:ffffffff]: accept: */*
00000001:static.srvrep[000c:000d]: HTTP/1.1 200 OK
00000001:static.srvhdr[000c:000d]: date: Sat, 03 Feb 2024 10:17:53 GMT
00000001:static.srvhdr[000c:000d]: server: Apache/2.4.58 (Unix)
00000001:static.srvhdr[000c:000d]: content-length: 481
00000001:static.srvhdr[000c:000d]: content-type: text/html;charset=ISO-8859-1
00000001:static.clicls[000c:000d]
00000001:static.srvcls[000c:000d]
00000001:static.closed[000c:000d]
```

If I do this now with `check_curl` I get:

```
HTTP WARNING: HTTP/1.1 400 Bad request - 207 bytes in 0.003 second response time |time=0.002838s;;;0.000000;10.000000 size=207B;;;0;
```

```
[01|h1|0|mux_h1.c:1598] parsing error, reject H1 message : [F,EMB] [MSG_RQVER, MSG_RPBEFORE]
[01|h1|0|mux_h1.c:1872] parsing or not-implemented error : [F,EMB] [MSG_RQVER, MSG_RPBEFORE]
[01|h1|0|mux_h1.c:3655] parsing error detected
```

I blame it on to restritive HTTP-header parsing, but it's hard to tell, as the
haproxy error messages are slightly crypric. :-)

**Comment by andreasbaumann** [comment]
Yep, sorry, my config just needes a `bind :80 accept-proxy` in forntend main. :-)
./check_curl --haproxy-protocol -vvv -I localhost -p 80 -u /
works. *thumbs up from my point".

How important is it to have something like support for setting the IP with CURLOPT_HAPROXY_CLIENT_IP?
as a --haproxy-client-ip=10.0.0.1 or so?

Sorry, I don't know literally nothing about haproxy, more a varnish guy here. :-)

**Review by andreasbaumann — APPROVED** [review]
fine for me.

**Comment by RincewindsHat** [comment]
Since you guys already created the configuration, would you like to add that to the test cases?

**Comment by emriver** [comment]
> Since you guys already created the configuration, would you like to add that to the test cases?

No sure how I can add this to the existing test cases, HTTP::daemon does not seem to handle proxy protocol.

**Comment by andreasbaumann** [comment]
The only option I personally see is to start a haproxy with the given minimal configuration. I'm not aware of a haproxy perl
stub server implementation. OTOH we could add the feature and just not test it. :-)

**Comment by sni** [comment]
tbh, i also don't think it's worth the effort to build a complicated test case here.

**Comment by RincewindsHat** [comment]
hm, ok, the let's go.

**Pull request merged**
