### PR TITLE
Fixed option description authpassword -> authpasswd + whitespaces

### PR DESCRIPTION
**Pull request by RincewindsHat**
#1551

### CODE REVIEW

**Comment by waja** [comment]
Can you please separate code style fixes from fixing something else. This is mostly an issue when reviewing code changes and backporting fixes to other branches for example.

Many thanks.

**Comment by RincewindsHat** [comment]
> Can you please separate code style fixes from fixing something else. This is mostly an issue when reviewing code changes and backporting fixes to other branches for example.
> 
> Many thanks.

I removed the whitespace changes as requested. Thank you :-)

**Comment by waja** [comment]
@sni do you think we should merge this into maint-2.3?

**Comment by sni** [comment]
yes, why not, it simpy fixes the help output and does not change the behaviour of the plugin itself

**Comment by RincewindsHat** [comment]
@waja: ping :-)

**Review by sni — APPROVED** [review]

**Pull request merged**
