### PR TITLE
check_http: Repair HTTP CONNECT function

### PR DESCRIPTION
**Pull request by mfrost8**
seems to be only partially in check_http.c.  That patch was at
http://sourceforge.net/p/nagiosplug/patches/336/ It also seems that the
single-letter variable I added (-K) is now taken by an other option.
I've switched to use the unused -B (the long argument format of
--http-connect is still valid) and re-inserted all the original changes
to allows checks through a proxy server that implements HTTP CONNECT
to work again.

### CODE REVIEW

**Comment by waja** [comment]
Thanks @mfrost8,

maybe you can also try to add the needed changes for the (now) failing test into this PR?

**Comment by lazyfrosch** [comment]
@waja This PR should be obsolete since 2.2

**Comment by waja** [comment]
> This PR should be obsolete since 2.2

Cause it was fixed there?

**Comment by waja** [comment]
This should be done with 342dd1b97fd3423cb6368fedbb6c729f3c3b6243

**Pull request closed without merging**
