### PR TITLE
check_apt: Add -l/--list option to print packages

### PR DESCRIPTION
**Pull request by vvidic**
Closes issue #1256

### CODE REVIEW

**Comment by waja** [comment]
@vvidic if it isn't too much hassle for you, can you please rebase your PR against master? This might fix the travis checks.

**Comment by vvidic** [comment]
Did a rebase but don't think that is the problem since there were no changes in ``check_apt.c``.

The build seems to be [failing](https://travis-ci.org/monitoring-plugins/monitoring-plugins/builds/155010658) during mariadb installation (version conflict between 5.5 and 5.6):

```
$ sudo apt-get install -qq --no-install-recommends mariadb-client mariadb-server
...
Selecting previously unselected package mariadb-server-5.5.
(Reading database ... 90642 files and directories currently installed.)
Preparing to unpack .../mariadb-server-5.5_5.5.53-1ubuntu0.14.04.1_amd64.deb ...
Aborting downgrade from (at least) 5.6 to 5.5.
If are sure you want to downgrade to 5.5, remove the file
/var/lib/mysql/debian-*.flag and try installing again.
dpkg: error processing archive /var/cache/apt/archives/mariadb-server-5.5_5.5.53-1ubuntu0.14.04.1_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
Selecting previously unselected package mariadb-client.
Preparing to unpack .../mariadb-client_5.5.53-1ubuntu0.14.04.1_all.deb ...
Unpacking mariadb-client (5.5.53-1ubuntu0.14.04.1) ...
Selecting previously unselected package mariadb-server.
Preparing to unpack .../mariadb-server_5.5.53-1ubuntu0.14.04.1_all.deb ...
Unpacking mariadb-server (5.5.53-1ubuntu0.14.04.1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/mariadb-server-5.5_5.5.53-1ubuntu0.14.04.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by waja** [comment]
@vvidic With #1457 we introduced filtering non-critical updates. Do you mind to implement support for that in your PR?

**Comment by waja** [comment]
@vvidic If you can submit an updated version until the mid of this week I can try to integrate such a change in the upcoming Debian stretch (9.x) release as the timewindow until the package freeze is  closing soon.

**Comment by vvidic** [comment]
OK, will try to resolve conflicts...

**Comment by vvidic** [comment]
Just merged the getopt string. The list option prints the packages in the default mode:

```
$ ./check_apt -l
APT WARNING: 144 packages available for upgrade (0 critical updates). |available_upgrades=144;;;0 critical_updates=0;;;0
ant
apt
apt-utils
busybox
...
```

The package list is also displayed if the --only-critical switch is set:
```
$ ./check_apt -o -l | head -n 5
APT OK: 144 packages available for upgrade (0 critical updates). |available_upgrades=144;;;0 critical_updates=0;;;0
ant
apt
apt-utils
busybox
...
```

**Comment by waja** [comment]
The idea was to list only the critical packages, if ```-o``` is specified. Which is what users might expect.

**Comment by vvidic** [comment]
On Mon, Jan 16, 2017 at 08:36:13AM -0800, waja wrote:
> The idea was to list only the critical packages, if ```-o``` is specified.
> Which is what users might expect.

Ok, patch updated to only list security updates when called with -l -o.

-- 
Valentin

**Comment by waja** [comment]
```
$ /tmp/check_apt 
APT WARNING: 28 packages available for upgrade (0 critical updates). |available_upgrades=28;;;0 critical_updates=0;;;0
$ /tmp/check_apt -o
APT OK: 28 packages available for upgrade (0 critical updates). |available_upgrades=28;;;0 critical_updates=0;;;0
$ /tmp/check_apt -l
APT WARNING: 28 packages available for upgrade (0 critical updates). |available_upgrades=28;;;0 critical_updates=0;;;0
base-files
base-passwd
binutils
default-libmysqlclient-dev
distro-info-data
iso-codes
libc-bin
libc-dev-bin
libc-l10n
libc6
libc6-dev
libdebconfclient0
libgcrypt20
libidn2-0
libp11-kit0
libperl5.24
libsystemd0
libtasn1-6
libudev1
locales
multiarch-support
mysql-common
openssh-client
perl
perl-base
perl-modules-5.24
perl-openssl-defaults
sudo
$ /tmp/check_apt -l -o
APT OK: 28 packages available for upgrade (0 critical updates). |available_upgrades=28;;;0 critical_updates=0;;;0
```

Seems to work as expected.

**Pull request merged**
