### PR TITLE
check_snmp: add 'multiplier' to modify current value

### PR DESCRIPTION
**Pull request by wnieder**
Sometimes the value returned by check_snmp should be modified to represent the actual value (e.g. an SNMP value of 1920 representing a temperature value of 19,2 °C). To avoid doing the modification in the next step I added an option (-M multiplier) to specify a float number. The current value in output and performance data is multiplied by this value which defaults to 1.0. Specifying values 0 < n < 1 will act as a divisor.

### CODE REVIEW

**Comment by sni** [comment]
I like the idea, but right now it turns all integers into floats. So i'd suggest to only apply the multiplier if its not 1. Also it would be nice to have a test case.

**Comment by canhastrytocode** [comment]
@wnieder Please finish this, i beg you :>

**Comment by sni** [comment]
could you please rebase onto latest head, travis tests should be much more stable now.

**Comment by RincewindsHat** [comment]
was replaced  by #1813

**Pull request closed without merging**
