### PR TITLE
timeout_alarm_handler(): return UNKNOWN on timeout

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
* [x] unit tests
* [x] master rebase

**Comment by sni** [comment]
while i agree with you, that a timeout should return unknown. I prefer a broader approach which would make the exit code configurable, like ex.: `./check_... -t 2:UNKNOWN` or something like that.

**Comment by Al2Klimov** [comment]
Hello @sni and thank you for your feedback!

If you agree, please approve this. IMO the configurability (if any) should be another PR.

Best,
AK

PS: Please see also #1494.

**Comment by sni** [comment]
I agreed that it should be unknown but i don't think its a good idea to change that globally now. If i would approve anything in that direction, it would be the solution mentioned above with the configurable exit code.

**Comment by waja** [comment]
@Al2Klimov are you still interested into get this integrated? If yes, @sni would be satisfied for shure if you change this accordingly https://github.com/monitoring-plugins/monitoring-plugins/pull/1543#issuecomment-403495471

**Comment by Al2Klimov** [comment]
I'm afraid:

**Pull request closed without merging**
