### PR TITLE
Check curl detect ipv6

### PR DESCRIPTION
**Pull request by RincewindsHat**
If an IPv6 address is give as `server_address` it must be surround by square brackets.

### CODE REVIEW

**Comment by RincewindsHat** [comment]
Resolves #1808

**Comment by sni** [comment]
Would it be possible to create a test case for this?

**Comment by RincewindsHat** [comment]
good question, afaik IPv6 is disabled in our testing setup and IPv6 in docker is generally a pain. I will investigate.

**Comment by RincewindsHat** [comment]
[This here](https://github.com/monitoring-plugins/monitoring-plugins/blob/edc84e5d669089fa3f047dc52740679e7cb58fc1/.github/prepare_debian.sh#L31) looks suspicios in that regard. I guess this is there to allow test using `localhost` as IP. Can we change that?

**Comment by RincewindsHat** [comment]
@sni I am currently out of ideas for this one. I think IPv6 is just to new for docker and Microsoft. I fear, we have to skip the test for now.
Can we add it conditionally to have it in different test environments?

**Comment by sni** [comment]
Sure, better than nothing :-)
There is a ipv6 test switch in check_tcp or check_dig already:
https://github.com/monitoring-plugins/monitoring-plugins/blob/master/plugins/t/check_tcp.t#L13

**Comment by RincewindsHat** [comment]
@sni should be fine now

**Review by sni — APPROVED** [review]

**Comment by sni** [comment]
looks good, thanks

**Pull request merged**
