### PR TITLE
Remove check for RETSIGTYPE in autoconf stuff

### PR DESCRIPTION
**Pull request by RincewindsHat**
autoupdate tells me, that since C89 I can safely assume RETSIGTYPE is void.

Therefore to simplify things I removed the corresponding configure.ac line and replaced all mentions of RETSIGTYPE with void.

### CODE REVIEW

**Comment by waja** [comment]
Looks like this is the case since a little... https://lists.isc.org/pipermail/inn-workers/2009-April/017010.html

**Comment by RincewindsHat** [comment]
it is.

**Comment by RincewindsHat** [comment]
@sni like to greenlight this?

**Review by sni — APPROVED** [review]
looks good to me

**Pull request merged**
