### PR TITLE
Implement option for check_snmp to ignore mib parsing errors (to fix test pipeline)

### PR DESCRIPTION
**Pull request by RincewindsHat**

### CODE REVIEW

**Comment by RincewindsHat** [comment]
@sni fixing the test is actually done in the last commit by changing the test.
Not quite sure about the other changes.
I would leave them there as "can't hurt", but what's your opinion on that?

**Comment by sni** [comment]
what other changes do you mean? The index++ changes? I am fine with this PR. Except i would remove the commented code. We have git now, no need keep dead code :-)

**Comment by RincewindsHat** [comment]
@sni done

**Review by sni — APPROVED** [review]

**Comment by sni** [comment]
On the long run it might be better to add one general option to pass through arguments to snmp instead of adding a new argument for each thing we want to set for snmp.
Besides that, i am fine :-)

**Pull request merged**
