### PR TITLE
Modified virtual host and port behaviour to match check_http.

### PR DESCRIPTION
**Pull request by odenbach**
Hope that's better. Sorry, still learning (and forgetting in between).

### CODE REVIEW

**Comment by sni** [comment]
perfect, thanks.

**Comment by odenbach** [comment]
Hi,

this is a modification of #1535. I made some changes regarding virtual hosts and virtual ports. The main change is the usage of CURLOPT_CONNECT_TO instead of CURLOPT_RESOLVE. As this function was introduced in version 7.49.0 (which is not included in e.g. Debian Jessie), I did not also add corresponding tests to the automatic test suite. It can however be easily tested by running the test suite manually:

```
odenbach@fenchurch:~/GIT/monitoring-plugins/plugins$ LC_ALL=C perl tests/check_curl.t -d
1..156
Please contact http at: <URL:http://127.0.0.1:50769/>
Please contact https at: <URL:https://127.0.0.1:50770/>
Please contact https expired at: <URL:https://127.0.0.1:50771/>

```
With unpatched check_curl:

```
odenbach@fenchurch:~/GIT/monitoring-plugins/plugins$ ./check_curl -H testhost:4444 -I localhost -p 50770 --ssl -u /virtual_port -r '^testhost:4444$' -v 
* Address in 'testhost:50770:localhost' found illegal!
* Could not resolve host: testhost
* Closing connection 0
HTTP CRITICAL - Invalid HTTP response received from host on port 50770: cURL returned 6 - Couldn't resolve host name

```
With patched check_curl:

```
odenbach@fenchurch:~/GIT/monitoring-plugins/plugins$ ./check_curl -H testhost:4444 -I localhost -p 50770 --ssl -u /virtual_port -r '^testhost:4444$' -v
* Connecting to hostname: localhost
* Connecting to port: 50770
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to testhost (127.0.0.1) port 50770 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=UK; ST=Derbyshire; L=Belper; O=Nagios Plugins; CN=Ton Voon; emailAddress=tonvoon@mac.com
*  start date: Mar  5 21:41:28 2009 GMT
*  expire date: Mar  3 21:41:28 2019 GMT
*  issuer: C=UK; ST=Derbyshire; L=Belper; O=Nagios Plugins; CN=Ton Voon; emailAddress=tonvoon@mac.com
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
> GET /virtual_port HTTP/1.1
Host: testhost:4444
User-Agent: check_http/v2.2.138.g1c554 (monitoring-plugins 2.2, libcurl/7.52.1 OpenSSL/1.0.2l zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3)
Accept: */*
Connection: close

< HTTP/1.1 200 OK
< Date: Tue, 12 Jun 2018 12:44:00 GMT
< Server: libwww-perl-daemon/1.00
* no chunk, no close, no size. Assume close to signal end
< 
* Curl_http_done: called premature == 0
* Closing connection 0
HTTP OK: HTTP/1.1 200 OK - 211 bytes in 0,025 second response time |time=0,024962s;0;0;; size=122B;;;

```
Please comment. Thanks for reviewing.

Cheers,
Christopher

P.S.: The failed travis build has nothing to do with my changes, I have no idea what causes the problem.

**Comment by sni** [comment]
i restarted the tests, they are fine now.

**Comment by ekeih** [comment]
> i restarted the tests, they are fine now.

Should we merge it? :)

**Comment by sni** [comment]
It seems like the modified `tests/check_curl.t` you were talking about is not included in this PR? Is that intentional? If not, could you add those changes as well since they also make sure it still works in the future.

**Comment by odenbach** [comment]
yes please :-)

**Comment by odenbach** [comment]
The problem with an automated test is that if somebody compiles the check with a libcurl version below 7.49.0 the check will fail because libcurl cannot do what is needed. If we all agree that version 7.49.0 is recent enough to make that a hard dependancy, I can of course implement the check.

**Comment by odenbach** [comment]
Can I easily check for the library version during the check?

**Comment by sni** [comment]
we could either put the tests into a `TODO { ... };` block or skip them for specific curl versions.

**Comment by odenbach** [comment]
```
./check_curl -V | grep libcurl | awk '{print $1}' | cut -f2 -d/
7.52.1

```
Yeah, ok, I'll go for it...

**Comment by sni** [comment]
yes, something like that. Maybe a simple regex in perl would be enough already.

**Comment by odenbach** [comment]
There you are. I put away my old virtual port tests as they do not work properly with too old curl versions and wrote some new ones. Tested with old curl and new one, with and without HTTP::Daemon::SSL. Worked always as expected.

**Comment by sni** [comment]
perfect, thanks.

**Pull request merged**
