### PR TITLE
check_disk: Fixing the stuff that is broken on btrfs

### LINKED ISSUE #1357: check_disk: sees wrong disk consumption on btrfs
In Debian we got reported (https://bugs.debian.org/800345) the following bugreport by Klaus Ethgen:

 Since several days, one of my checks went red for one of my boxes,
mentioned that / is 100% full. But this is not true, there is plenty of
space left.

   ~> df -Th
   Filesystem               Type      Size  Used Avail Use% Mounted on
   /dev/sda1                btrfs     502M  338M  169M  67% /
   ...

   ~> btrfs fi df /
   System, single: total=4.00MiB, used=4.00KiB
   Data+Metadata, single: total=497.81MiB, used=329.71MiB
   GlobalReserve, single: total=8.00MiB, used=0.00B

   ~> /usr/lib/nagios/plugins/check_disk -w '3%' -c '1%'
   DISK CRITICAL - free space: / 0 MB (0% inode=-)]; ...

   ~> grep ' / ' /proc/mounts
   /dev/sda1 / btrfs rw,nodiratime,relatime,compress=zlib,ssd,discard,space_cache,autodefrag 0 0

All other partitions worked well but it constantly shows / to be full.

   ~> /usr/lib/nagios/plugins/check_disk -w '3%' -c '1%' -vvv
   Thresholds(pct) for / warn: 3,000000 crit 1,000000
   calling stat on /
   For /, used_pct=100 free_pct=0 used_units=337 free_units=0 total_units=501 used_inodes_pct=-1 free_inodes_pct=101 fsp.fsu_blocksize=4096 mult=1048576
   Freespace_units result=0
   Freespace% result=2
   Usedspace_units result=0
   Usedspace_percent result=0
   Usedinodes_percent result=0
   Freeinodes_percent result=0

And to give you what stat gives:
   ~> stat -f /
     File: "/"
       ID: a446833a80ceeb6a Namelen: 255     Type: btrfs
   Block size: 4096       Fundamental block size: 4096
   Blocks: Total: 128472     Free: 42014      Available: 43031
   Inodes: Total: 0          Free: 0

I think, I found the bug.

line [1044](https://github.com/monitoring-plugins/monitoring-plugins/blob/master/plugins/check_disk.c#L1087):
   p->available = fsp->fsu_bavail > fsp->fsu_bfree ? 0 : fsp->fsu_bavail;

But from the stat I see that:
   ... Free: 41708      Available: 42725

I think, that BDE^HD workarround here is broken for btrfs and maybe
other filesystems that supports compression.

### PR DESCRIPTION
**Pull request by waja**
This patch was shared by Klaus Ethgen (@mowgli) at  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800345#29

(Closes #1357)

### CODE REVIEW

**Comment by mowgli** [comment]
Please note that this is fixing the btrfs problem by removing the workaround on bsd. While that would be great for debian, I am not sure about if that is true for bsd too.

**Comment by waja** [comment]
@mowgli Debian has still kfreebsd, so this even might break it there and so it might be not a solution we want to use in Debian.

**Comment by mowgli** [comment]
That is true, waja, but we don't have bsd glibc. And from the comment I do not think that debian is affected by the problem that was the source for workaround introduced in 2007(!).

From how old that problem is, I even suspect it been fixed in bsd too. However, I do not have any bsd around so I cannot test that.

However, that commit from 2007 seems to be somewhat blue eyed. So please one with access to bsd, check if that assumption in the comment is still valid.

BTW, commit is dbc22e1.

**Comment by dannyman** [comment]
I had a half dozen BTRFS filesystems go red on me. But they're nowhere near full. And apparently, this is because of a 14-year-old workaround for BSD, which has a fix proposed six years back. :)

This is just to say: I support this PR.

**Comment by sni** [comment]
alright, lets merge it then...

**Comment by DocMAX** [comment]
Still not fixed:
```
docmax@zeus: ~ $ sudo /usr/lib/monitoring-plugins/check_disk -w '3%' -c '1%' -N btrfs
DISK CRITICAL - free space: / 242961 MB (26% inode=-); /mnt/zeus/hdd 0 MB (0% inode=-)]; /mnt/zeus/4bay_usb3 512466 MB (7% inode=-); /mnt/zeus/8bay_usb3 11474999 MB (21% inode=-);| /=679683MB;915175;934045;0;943480 /mnt/zeus/hdd=1821090MB;3700983;3777292;0;3815447 /mnt/zeus/4bay_usb3=6164779MB;9252475;9443248;0;9538635 /mnt/zeus/8bay_usb3=41954013MB;59215669;60436611;0;61047082
docmax@zeus: ~ $ LANG= sudo df -h /mnt/zeus/hdd/
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda        3.7T  1.8T  2.0T  48% /mnt/zeus/hdd
```

**Comment by waja** [comment]
> Still not fixed:
> 
> ```
> docmax@zeus: ~ $ sudo /usr/lib/monitoring-plugins/check_disk -w '3%' -c '1%' -N btrfs
> DISK CRITICAL - free space: / 242961 MB (26% inode=-); /mnt/zeus/hdd 0 MB (0% inode=-)]; /mnt/zeus/4bay_usb3 512466 MB (7% inode=-); /mnt/zeus/8bay_usb3 11474999 MB (21% inode=-);| /=679683MB;915175;934045;0;943480 /mnt/zeus/hdd=1821090MB;3700983;3777292;0;3815447 /mnt/zeus/4bay_usb3=6164779MB;9252475;9443248;0;9538635 /mnt/zeus/8bay_usb3=41954013MB;59215669;60436611;0;61047082
> docmax@zeus: ~ $ LANG= sudo df -h /mnt/zeus/hdd/
> Filesystem      Size  Used Avail Use% Mounted on
> /dev/sda        3.7T  1.8T  2.0T  48% /mnt/zeus/hdd
> ```

@DocMAX and you tested it how? You did compile `master` for yourself?

**Pull request merged**
