### PR TITLE
check_tcp: add --sni

### LINKED ISSUE #1510: check_tcp SNI support
Many SSL servers now use SNI to deliver certs.  This can cause an issue when using check_tcp.  If not using SNI check_tcp may be comparing against the wrong certificate for expire dates.

A discussion around SNI and the differences between nagios-plugins and monitoring-plugins for this feature took place at:
https://github.com/Icinga/icinga2/issues/5577

For an example, you can see that trying to check the icinga.org certificate check_tcp actually checks the icinga.com certificate without SNI support.

```
/usr/lib/nagios/plugins/check_tcp -H icinga.org -p 443 --ssl -D 90,30
OK - Certificate '*.icinga.com' will expire on Thu 26 Dec 2019 11:59:00 PM STD.
TCP OK - 0.616 second response time on icinga.org port 443|time=0.615661s;;;0.000000;10.000000
```
The version of check_tcp I tested with:
```
/usr/lib/nagios/plugins/check_tcp -V
check_tcp v2.1.2 (monitoring-plugins 2.1.2)
```

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #1510

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Before

```
➜  monitoring-plugins git:(master) plugins/check_tcp -H 78.46.175.9 -p 443 -S -D 7,3
OK - Certificate 'TRAEFIK DEFAULT CERT' will expire on Di 29 Dez 12:12:01 2020 +0000.
TCP OK - 0,089 second response time on 78.46.175.9 port 443|time=0,089186s;;;0,000000;10,000000
➜  monitoring-plugins git:(master)
```

## After

```
➜  monitoring-plugins git:(feature/tcp-sni) plugins/check_tcp -H 78.46.175.9 -p 443 -S -D 7,3 -N al2klimov.de
OK - Certificate 'al2klimov.de' will expire on Sa 14 Mär 17:00:56 2020 +0000.
TCP OK - 0,102 second response time on 78.46.175.9 port 443|time=0,101815s;;;0,000000;10,000000
➜  monitoring-plugins git:(feature/tcp-sni)
```

**Comment by sni** [comment]
thanks, looks good. Just one thing, i'd say use `--sni` only and remove the `-N`, thats how the argument is defined in `check_http`.

**Comment by Al2Klimov** [comment]
@dnsmichi This PR fixes https://github.com/Icinga/icinga2/pull/5578#issuecomment-345340266, https://github.com/Icinga/icinga2/pull/5578#issuecomment-385919091 and my private setup. It wouldn't be a problem for me to remove `-N` here, but would it be a problem to use `--sni` instead of `-N` in the ITL? @mcktr talked about a [check_tcp version from the monitoring-plugins](https://github.com/Icinga/icinga2/pull/5578#issuecomment-330137121). Is there another version we shall care about or can we just use `--sni` in the ITL?

**Comment by dnsmichi** [comment]
I don't mind, go for it.

**Comment by Al2Klimov** [comment]
@sni Done.

@dnsmichi So I'll adjust the ITL as soon as this one gets merged.

**Comment by sni** [comment]
thanks

**Pull request merged**
