### PR TITLE
check_nwstat: adds percentage used space

### PR DESCRIPTION
**Pull request by waja**
Just turning attached patch of github issue #918 into a push request.

"This adds the new VPU parameter to the check_nwstat plugin. This parameter returns the percentage used space on a Netware volume.
Now you can monitor your Netware volumes easy. We use it with a warning 85% and critical 90%.
eg: `check_nwstat -H your.netware.host -v VPUvol1 -c 85 -w 90` returns
`324653 MB (95%) used on volume vol1 - total 340212 MB|Used space in percent on vol1=95;90;80;0;100.`"

### CODE REVIEW

**Comment by RincewindsHat** [comment]
@waja would you like to update this? Sounds harmless enough

**Comment by RincewindsHat** [comment]
Fixes #918

**Comment by waja** [comment]
> @waja would you like to update this? Sounds harmless enough

With "update" you mean to solve the merge conflict? I did. :)

**Comment by RincewindsHat** [comment]
@waja github tells me this has merge conflicts :-)

**Comment by waja** [comment]
Indeed. At the point we started to force translation updates in the PRs, the chance that those are having merge conflicts are very likely.

**Comment by waja** [comment]
@RincewindsHat here we are!

**Comment by RincewindsHat** [comment]
@waja is there a button here which allows me to push to that branch?

**Comment by waja** [comment]
I allowed write access to maintainers for this PR.

**Comment by RincewindsHat** [comment]
ok, I would merge this, maybe there is someone out there who still has a Netware installation and can use this.
This is completely untested.

**Review by RincewindsHat — APPROVED** [review]
Untested in a real life scenario!
Might be useful though if someone still has that kind of thing.

**Pull request merged**
