### PR TITLE
sslutils: optimize output if certificate expires in less then 24h

### PR DESCRIPTION
**Pull request by m4c3**
optimize output if certificate expires in less then 24h
thx to axel schmalowsky for this patch

### CODE REVIEW

**Comment by sni** [comment]
I like the idea. After a quick look, i think the code will print wrong information if the time till expire is below one hour. It would then print "minutes" as unit but stil print the hours_left.
Also i am not a fan of cascaded if statements. I would at least break it on several lines.

**Comment by m4c3** [comment]
this looks like a temporary failure with travis or the mozilla test url
can you restart the build?

**Comment by weiss** [comment]
Done (and it helped).

**Comment by sni** [comment]
thanks, PR has been merged.

**Pull request closed without merging**
