### PR TITLE
Add support for SNI in check_smtp

### PR DESCRIPTION
**Pull request by franzs**
Add support for SSL/TLS hostname extension support (SNI) for check_smtp
plugin.

Backported from nagios-plugins:
https://github.com/nagios-plugins/nagios-plugins/commit/9f1628f4b5525335ce1d6e48e8ac8b07d0757f82

Compiled and successfully tested new `--sni` option

### CODE REVIEW

**Comment by franzs** [comment]
Hi @lorenz, is there any chance to get another review from you? Meanwhile I prepared three more branches with additional features/bugfixes from nagios-plugins for check_smtp. 😇

**Comment by lorenz** [comment]
Are you confusing me with someone else? I don't have anything to do with this project.

**Comment by franzs** [comment]
Oh, yes, I'm sorry, @lorenz.

**Comment by RincewindsHat** [comment]
Probably I am targeted :-) Sorry, didn't have the time and nerves yet. It's on my list

**Review by RincewindsHat — APPROVED** [review]
Looks good to me

**Comment by RincewindsHat** [comment]
Thank you very much.

**Comment by franzs** [comment]
Thanks a lot for reviewing and merging, @RincewindsHat 😃

**Comment by waja** [comment]
[ee8d2e8](https://github.com/monitoring-plugins/monitoring-plugins/pull/1887/commits/ee8d2e8ec1e27586e2f9f5865c45d245a3492ec3) is very unfortune here ... it makes the patchset kinda un(back)portable ...

**Comment by franzs** [comment]
@waja maybe we should head over the discussion to PR #1889. this PR is still open and I took the same approach there.

**Pull request merged**
