### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by glensc**
sudo for `[` seemed wrong, refs 20d8799

### CODE REVIEW

**Comment by sni** [comment]
I'd say both works. Your solution is nicer because it doesn't run grep and wc with sudo. But we can just remove sudo completly, because `ip addr show` works with user permissions as well and we just need to keep the sudo before the `sed`.

**Comment by sni** [comment]
And it seems like yaml does not want a string to start with [. So i'd say we leave things as they are.

**Comment by ckujau** [comment]
Assuming that ```/etc/hosts``` is only modified on the TravisCI system, what about:

``ip addr show | grep -q "inet6 ::1" && sudo sed -i '/^::1/d' /etc/hosts```

**Comment by glensc** [comment]
@sni you should understand how shell parser works. wc and grep are not ran under sudo, they are next command in pipe chain, if *want* them to run under sudo, you must prepend sudo to each of them

why it works is likely "ip" command does not require root access, and sudo will just include `/sbin` in path so the program is visible. solution: use abs path.

however i kept sudo, because depending on kernel hardening `ip` via `sudo` may give more information than under normal user.

**Comment by glensc** [comment]
if travis does not like `[` then the line can be replaced with:

```
- test $(sudo ip addr show | grep "inet6 ::1" | wc -l) -lt "1" && sudo sed -i '/^::1/d' /etc/hosts
```

**Comment by qha** [comment]
You might also consider replacing
  `grep "inet6 ::1" | wc -l`
with 
  `grep -c "inet6 ::1"`

**Pull request closed without merging**
